swiftmailer:
    transport: '%env(SENDGRID_TRANSPORT)%'
    host:      '%env(SENDGRID_HOST)%'
    username:  '%env(SENDGRID_USERNAME)%'
    password:  '%env(SENDGRID_API_KEY)%'
    port:      '%env(SENDGRID_PORT)%'
    encryption: '%env(SENDGRID_ENCRYPTION)%'
    spool: { type: 'memory' }
