App\Entity\Comment:
    properties:
        content:
            - NotBlank: ~

App\Entity\Picture:
    properties:

App\Entity\Trick:
    properties:
        name:
            - NotBlank: ~
        category:
            - NotBlank: ~
        description:
            - NotBlank: ~
        picture:
            - NotBlank: ~
        video:
            - NotBlank: ~

App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: userName
            message: Le nom d'utilisateur {{ value }} est déjà utilisé.
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: mail
            message: Le mail "{{ value }}" est déjà utilisé par un utilisateur.
    properties:
        userName:
            - NotBlank: ~
        mail:
            - NotBlank: ~
        plainPassword:
            - NotBlank: ~
            - Length:
                min: 6
                max: 12
                minMessage: 'Le mot de passe doit comporter au moins {{ limit }} caractères'
                maxMessage: 'Le mot de passe ne doit pas dépasser les {{ limit }} caractères'

App\Entity\Video:
    properties:
        url:
            - Url: ~
