home:
    path: /
    defaults: { _controller: 'App\Controller\TrickController::tricks' }

trick_detail:
    path: /trick/detail/{id}
    defaults: { _controller: 'App\Controller\TrickController::detailTrick' }
    requirements:
        id: '\d+'

trick_add:
    path: /trick/add
    defaults: { _controller: 'App\Controller\TrickController::addTrick' }

trick_update:
    path: /trick/update/{id}
    defaults: { _controller: 'App\Controller\TrickController::updateTrick' }
    requirements:
        id: '\d+'

trick_delete:
    path: /trick/delete/{id}
    defaults: { _controller: 'App\Controller\TrickController::deleteTrick'}
    requirements:
        id: '\d+'

picture_delete:
    path: /picture/delete/{id_picture}/trick/{id_trick}
    defaults: { _controller: 'App\Controller\PictureController::deletePicture'}
    requirements:
        id_picture: '\d+'
        id_trick: '\d+'

video_delete:
    path: /video/delete/{id_video}/trick/{id_trick}
    defaults: { _controller: 'App\Controller\VideoController::deleteVideo'}
    requirements:
        id_video: '\d+'
        id_trick: '\d+'

registration:
    path: /registration
    defaults: { _controller: 'App\Controller\SecurityController::registration' }

login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::login' }

forgot_password:
    path: /forgot/password
    defaults: { _controller: 'App\Controller\SecurityController::forgotPassword' }

reset_password:
    path: /reset/password
    defaults: { _controller: 'App\Controller\SecurityController::resetPassword' }
