App\Entity\Comment:
    type: entity
    repositoryClass: App\Repository\CommentRepository
    table: comment
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        content:
            type: text
        creationDate:
            type: datetime
            name: creation_date
    manyToOne:
        trick:
            targetEntity: App\Entity\Trick
            inversedBy: comment
            joinColumn:
                name: trick_id
                referencedColumnName: id
        user:
            targetEntity: App\Entity\User
            inversedBy: comment
            joinColumn:
                name: user_id
                referencedColumnName: id
